# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Gearman
version:      1.11
version_from: lib/Gearman/Client.pm
installdirs:  site
requires:
    String::CRC32:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
